language: bash

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t tibbar/gravitywell:latest .
  - docker push tibbar/gravitywell:latest
