--- 
before_install: 
  - "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin"
  - "cat VERSION | xargs -I{} docker build -t tibbar/gravitywell:{} ."
  - "cat VERSION | xargs -I{} docker push tibbar/gravitywell:{}"
  - "docker build -t tibbar/gravitywell:latest ."
  - "docker push tibbar/gravitywell:latest"
language: bash
services: 
  - docker
