APIVersion: "v1"
Kind: "ActionList"
Executions:
  - Execute:
    Kind: "RunActionList"
    Configuration:
      Path: deployment #Optional value
      AwaitDeployment: true #Optional defaults to false