APIVersion: "v1"
Kind: "ActionList"
Executions:
  - Execute:
    Kind: "Shell"
    Configuration:
      Command: ./build_environment.sh small
  - Execute:
    Kind: "RunActionList"
    Configuration:
      Path: examples/common/templates/actionlist/actionlist-deployment.yaml